language: node_js
sudo: false

notifications:
  email:
    recipents:
      - y1j2x34@qq.com
  on_success: change
  on_failure: always

node_js:
  - "8"

install:
  - npm install -g npm
  - npm install


script:
  - npm test
